[project]
name = "llm"
version = "0.1.0"
requires-python = ">=3.13"

dependencies = [
    "numpy>=2.4.2",
    "pydantic>=2.12.5",
    "regex>=2026.2.19",
    "rich>=14.3.3",
    "tqdm>=4.67.3",
]

[project.optional-dependencies]
jax_cuda12 = [
    "flax>=0.12.2",
    "jax[cuda12]>=0.9.0",
    "optax>=0.2.5",
]
matplotlib = [
    "matplotlib>=3.10.8"
]
tensorboard = [
    "tensorboard>=2.20.0",
]
torch_cpu = [
    "torch>=2.10.0",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "ruff>=0.15.2",
]

[tool.ruff.lint]
extend-select = [
    "I"
]
